# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  nameOverride: ""
  fullnameOverride: ""

  # -- Domain suffix to be used for default hostpaths in ingress
  # override in different environments, or for each app
  # --set global.ingressSuffix
  ingressSuffix: -tools.apps.silver.devops.gov.bc.ca

  persistence:
    # -- If true, the Postgres chart is deployed
    deployPostgres: true

  # -- The used ledger. Will be used for default values.
  ledger: bcovrin-test

traction:

  config:
    ledger:
      browserUrlOverride: ""
      genesisUrlOverride: ""
    # -- The scheme that is used to register the profile endpoint on the ledger
    scheme: https

  imagePullSecrets: []

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    # Uncomment this to define your own hosts and override global.ingressSuffix
    # hosts:
    #     host:
    #     paths: ['/']
    tls: []
    #  - secretName: my-bpa-tls
    #    hosts:
    #      - my-bpa.local

  openshift:
    route:
      enabled: true
      path: "/"
      targetPort: http
      timeout: 2m
      tls:
        enabled: true
        insecureEdgeTerminationPolicy: None
        termination: edge
      wildcardPolicy: None

  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}
    
acapy:
  image:
    repository: bcgovimages/aries-cloudagent
    pullPolicy: IfNotPresent
    # --  Overrides the image tag whose default is the chart appVersion.
    tag: py36-1.16-1_0.7.1

  adminURLApiKey: 2f9729eef0be49608c1cffd49ee3cc4a


  # The agent seed, 32 characters. Will be generated if not defined here
  agentSeed: ""

  labelOverride: ""

  readOnlyMode: false

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000


  securityContext:
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1001

  service:
    type: ClusterIP
    adminPort: 8031
    httpPort: 8030

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"

    # Uncomment this to define your own hosts and override global.ingressSuffix
    # hosts:
    #     host:
    #     paths: ['/']
    tls: []
    #  - secretName: my-acapy-tls
    #    hosts:
    #      - my-acapy.local

  openshift:
    route:
      enabled: true
      path: "/"
      targetPort: http
      timeout: 2m
      tls:
        enabled: true
        insecureEdgeTerminationPolicy: None
        termination: edge
      wildcardPolicy: None

  tails:
    # -- Set to true to enable revocation (external tails server required)
    enabled: false

    # -- Override the otherwise ledger-specifically generated base URL of the external tails server
    baseUrlOverride: ""

    # -- Override the otherwise ledger-specifically generated upload URL of the external tails server
    uploadUrlOverride: ""

  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  staticArgs:
    autoAcceptInvites: true
    autoAcceptRequests: true
    autoRespondMessages: true
    autoRespondCredentialProposal: true
    autoRespondCredentialOffer: true
    autoRespondCredentialRequest: true
    autoRespondPresentationProposal: true
    autoRespondPresentationRequest: true
    autoStoreCredential: true
    autoVerifyPresentation: true
    autoPingConnection: true
    autoProvision: true
    monitorPing: true
    publicInvites: true
    logLevel: info

postgresql:
  # --  PostgreSQL service configuration
  service:
    port: 5432

  # --  PostgreSQL User to create. Do not change - otherwise non-admin user is created!
  postgresqlUsername: postgres

  # --  PostgreSQL Password for the new user. If not set, a random 10 characters password will be used.
  postgresqlPassword: change-me

  # -- PostgreSQL Database to create.
  postgresqlDatabase: traction

  # --  Persistent Volume Storage configuration. ref: https://kubernetes.io/docs/user-guide/persistent-volumes
  persistence:

    # -- Enable PostgreSQL persistence using Persistent Volume Claims.
    enabled: true
    size: 1Gi
    storageClass: netapp-file-standard
  image:
    tag: 12
  # -- add securityContext (fsGroup, runAsUser). These need to be false for Openshift 4
  securityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  resources:
    limits:
      cpu: 100m
      memory: 384Mi
    requests:
      cpu: 50m
      memory: 256Mi
